import {passengerStats,hourProfile,annualExcess,routeName,scopeText} from './insights.mjs';
import {searchLines,aggregate,archiveGeometry} from './model.mjs';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>n==null?'לא זמין':Number(n).toLocaleString('he-IL',{maximumFractionDigits:1});
const pct=(a,b)=>b?num(100*a/b)+'%':'אין מדידות';
// Read generated JSON from the public source repository so daily bot updates do not depend on a Pages rebuild.
const dataURL=url=>new URL(url.startsWith('../')?url.slice(3):'lines/'+url,'https://raw.githubusercontent.com/Transit-Freak/kav-bochan/main/').href;
const cache=new Map();async function load(url){if(!cache.has(url))cache.set(url,fetch(dataURL(url),{cache:'no-cache',signal:AbortSignal.timeout(25000)}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).catch(e=>{cache.delete(url);throw e}));return cache.get(url)}
let index,record,tab='overview',variant='',day='',busIndex=null,map=null,epoch=0,resultLimit=24;
const tabs=[['overview','הקו במבט אחד'],['reliability','מגיע בזמן?'],['passengers','כמה נוסעים?'],['scores','מה אומרים המדדים?'],['overlaps','קווים דומים']];
const table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(x=>`<td>${x}</td>`).join('')+'</tr>').join('')}</tbody></table></div>`;
const card=(title,value,desc,cls='')=>`<div class="card ${cls}"><h3>${esc(title)}</h3><b>${esc(value)}</b><small>${esc(desc)}</small></div>`;
const note=s=>`<p class="note">${esc(s)}</p>`;
const error=(el,retry,text='המידע לא נטען. אפשר לנסות שוב.')=>{el.innerHTML=`<div class="error"><p>${esc(text)}</p><button>ניסיון נוסף</button></div>`;el.querySelector('button').onclick=retry};
function results(){const rows=searchLines(index.lines,$('#query').value);$('#status').textContent=`${num(rows.length)} קווים נמצאו. בחרו קו כדי להכיר אותו מקרוב.`;$('#results').innerHTML=rows.slice(0,resultLimit).map(r=>`<button class="result" data-mk="${esc(r.makat)}"><span class="number">${esc(r.number)}</span><span><b>${esc(r.origin&&r.dest?r.origin+' ← '+r.dest:r.cities.slice(0,3).join(' · ')||'פרטי הקו')}</b><small>${esc(r.agencies.join(' · '))}</small><small>מק״ט ${esc(r.makat)}${r.removed?' · היסטורי / בוטל':''}</small></span></button>`).join('')+(rows.length>resultLimit?'<button id="more">הצגת קווים נוספים</button>':'');$('#results').querySelectorAll('[data-mk]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.mk});if($('#more'))$('#more').onclick=()=>{resultLimit+=24;results()};}
$('#searchForm').onsubmit=e=>{e.preventDefault();resultLimit=24;closeDetail();results()};
let typing;$('#query').oninput=()=>{clearTimeout(typing);typing=setTimeout(()=>{resultLimit=24;results()},180)};
function closeDetail(){epoch++;record=null;map?.remove();map=null;document.body.classList.remove('line-open');$('#methodLink').href='method.html';$('#detail').hidden=true;$('#results').hidden=false;history.replaceState(null,'',location.pathname+location.search);}
async function openLine(mk){const n=++epoch;const r=index.lines.find(r=>r.makat===mk);if(!r){$('#status').textContent='המק״ט שבקישור אינו נמצא בקטלוג.';return}document.body.classList.add('line-open');$('#detail').hidden=false;$('#results').hidden=true;$('#detail').innerHTML='<p role="status">טוען את פרטי הקו…</p>';try{const b=await load(`data/${r.bucket}.json?v=${index.files[r.bucket]}`);if(n!==epoch)return;record=b[mk];tab='overview';variant='';render();$('#detail').scrollIntoView({block:'start',behavior:'smooth'});}catch(e){if(n===epoch)error($('#detail'),()=>openLine(mk))}}
function render(){
 epoch++;map?.remove();map=null;const r=record;$('#methodLink').href='method.html#'+encodeURIComponent(r.makat);
 $('#detail').innerHTML=`<div class="line-actions"><button class="back" id="back">→ חזרה לקווים</button><span class="line-id">מספר זיהוי במשרד התחבורה: ${esc(r.makat)}</span></div>
 <div class="linehead"><div class="line-sign"><small>קו</small><span>${esc(r.number)}</span></div><div class="line-title"><span class="eyebrow">מכירים את הקו</span><h2>${esc(r.origin&&r.dest?r.origin+' ← '+r.dest:routeName(r.variants[0]?.name)||'פרטי הקו')}</h2><p>${esc(r.agencies.join(' · ')||'המפעיל לא מופיע במקור הזה')}</p><div class="tags">${[...new Set(r.variants.map(v=>v.type).filter(Boolean))].map(t=>`<span>${esc(t)}</span>`).join('')}${r.district?`<span>${esc(r.district)}</span>`:''}</div></div><div class="ticket-stamp" aria-hidden="true">הקו<br>מקרוב<span>↗</span></div></div>
 ${r.live?.rm?note('הקו מסומן כמבוטל. אפשר עדיין לעיין במידע שנשמר עליו.'):''}
 <nav class="tabs" aria-label="פרטי הקו">${tabs.map(([id,name],i)=>`<button data-tab="${id}" aria-pressed="${tab===id}"><span class="tab-stop" aria-hidden="true">${String(i+1).padStart(2,'0')}</span>${name}</button>`).join('')}</nav><div id="body"></div>`;
 $('#back').onclick=closeDetail;bindTabs();const body=$('#body');
 if(tab==='overview')overview(body);if(tab==='scores')scores(body);if(tab==='passengers')passengers(body);if(tab==='reliability')reliability(body);if(tab==='overlaps')overlaps(body);
}
function bindTabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});}
const fact=(label,value,help='')=>`<div class="fact"><dt>${esc(label)}</dt><dd>${esc(value)}</dd>${help?`<small>${esc(help)}</small>`:''}</div>`;
const scope=g=>scopeText(g)?note(scopeText(g)):'';
function hourlyChart(rows){const hours=hourProfile(rows);if(!hours.length)return note('אין פירוט לפי שעות במקור הזה.');const max=Math.max(1,...hours.map(x=>x.avg));return `<div class="hour-chart" role="img" aria-label="ממוצע נוסעים לנסיעה לפי שעת יציאה">${hours.map(x=>`<div class="hour-column"><span>${num(x.avg)}</span><i style="height:${Math.max(2,Math.round(100*x.avg/max))}%"></i><b>${String(x.hour).padStart(2,'0')}</b></div>`).join('')}</div><p class="caption">השעה מתחת לעמודה, ומספר הנוסעים הממוצע מעליה.</p>`;}

function links(){const mk=encodeURIComponent(record.makat);return `<div class="links"><a href="../#פח/קו/${mk}">פתיחה בקו פח</a><a href="../#מוזהב/קו/${mk}">פתיחה בקו המוזהב</a><a href="../bus/">למדד האמינות המלא</a><a href="../line-history/">להיסטוריית הקווים</a></div>`;}
function overview(el){
 const r=record,a=passengerStats(r.schedule),g=r.groups.length===1?r.groups[0]:null;
 el.innerHTML=`<div class="overview-layout"><div class="overview-main"><section id="quickReliability" class="panel service-panel" aria-live="polite">טוען את נתוני השירות…</section>
 <section class="panel passenger-panel"><div class="section-heading"><div><span class="eyebrow">הנוסעים</span><h2>כמה משתמשים בקו?</h2></div><span class="date-chip">${esc(index.passengerPeriod)}</span></div><div class="big-pair"><div><b>${num(a.avg)}</b><span>נוסעים בממוצע בנסיעה</span></div><div><b>${num(a.peak)}</b><span>בקטע העמוס, בממוצע</span></div></div><dl class="facts">${fact('נסיעות בשבוע',a.count?num(a.count):'אין נתונים','בתקופת מדידת הנוסעים')}${fact('נסיעות ביום בעדכון האחרון',r.live?.ntr>0?num(r.live.ntr):'אין נתון',index.liveUpdated)}</dl><button class="text-button" data-tab="passengers">באילו שעות נוסעים יותר? ←</button></section>
 <section class="panel"><div class="section-heading"><div><span class="eyebrow">שתי זוויות על אותו קו</span><h2>קו פח והקו המוזהב</h2></div></div>${g?scope(g)+`<div class="score-preview"><div class="pach"><span>קו פח</span><strong>${g.sc?num(g.sc.score)+'/100':'אין ציון'}</strong><small>ככל שהציון גבוה יותר, השימוש במשאבים פחות יעיל לפי המדד.</small></div><div class="gold"><span>הקו המוזהב</span><strong>${g.gold?num(g.gold.score)+'/100':'לא נכנס לדירוג'}</strong><small>${g.gold?'הקו עובר את תנאי הסף של דירוג הקווים המצטיינים.':'המשמעות היא שלא עבר את תנאי הדירוג, לא שקיבל אפס.'}</small></div></div>`:note(r.groups.length?'יש לקו כמה קבוצות מדידה. הפירוט נמצא בלשונית המדדים.':'אין לקו נתונים לחישוב הציונים.')}<button class="text-button" data-tab="scores">עלויות, נסיעות דלילות והסבר לציון ←</button></section></div>
 <aside class="overview-aside"><div id="routePreview"></div><section class="small-print"><h3>שימו לב לתאריך</h3><p>הנוסעים והעלויות נמדדו ב־${esc(index.passengerPeriod)}. ליד נתוני השירות והמפה מופיע התאריך שלהם.</p></section></aside></div>`;
 bindTabs();quickReliability();route($('#routePreview'),true);
}

async function getDays(){busIndex ||= await load('../bus/data/index.json');const ds=busIndex.days.map(x=>typeof x==='string'?{d:x}:x).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x.d)).sort((a,b)=>a.d.localeCompare(b.d));if(!day||!ds.some(x=>x.d===day))day=ds.at(-1)?.d||'';return ds;}
function rowsFor(d,selected=variant){const ids=new Set(record.variants.filter(v=>!selected||v.rid===selected).map(v=>v.rid));return d.routes.filter(r=>ids.has(String(r[0])))}
function serviceStory(a,date){
 const late=a.c.slice(2).reduce((x,y)=>x+y,0),miss=Math.max(0,a.sched-a.obs);
 return `<div class="section-heading"><div><span class="eyebrow">השירות בפועל</span><h2>מגיע בזמן?</h2></div><span class="date-chip">${esc(date)}</span></div><div class="service-lead"><div class="hero-value">${pct(a.c[1],a.meas)}</div><p>מההגעות שנמדדו<br><strong>היו בזמן</strong></p></div><div class="delay-strip" aria-hidden="true">${a.c.map((v,i)=>`<i class="delay-${i}" style="flex:${v}"></i>`).join('')}</div><div class="delay-legend"><span><i class="delay-1"></i>בזמן ${pct(a.c[1],a.meas)}</span><span><i class="delay-2"></i>באיחור ${pct(late,a.meas)}</span><span><i class="delay-0"></i>מוקדם ${pct(a.c[0],a.meas)}</span></div><p class="caption">נבדקו ${num(a.meas)} הגעות לתחנות.</p><dl class="facts">${fact('נסיעות שנצפו',num(a.obs)+' מתוך '+num(a.sched),'לפי שידורי המיקום')}${fact('נסיעות שלא נצפו',num(miss),'ייתכן גם חוסר בשידורים')}${fact('איחור ממוצע',a.weighted?num(a.sum/a.weighted)+' דק׳':'אין מדידות','מספר שלילי מציין הקדמה')}</dl>${a.sched>0&&a.obs<a.sched*.3?note('מעט מהנסיעות שידרו מיקום ביום הזה. ייתכן שהנתונים חלקיים.'):''}`;
}
async function quickReliability(){const n=epoch,el=$('#quickReliability');try{const days=await getDays();if(n!==epoch)return;const latest=days.at(-1)?.d;if(!latest){el.textContent='עדיין אין מדידות שירות.';return}const d=await load('../bus/data/days/'+latest+'.json');if(n!==epoch)return;const rows=rowsFor(d,'');if(!rows.length){el.innerHTML=note('אין מדידה לקו ביום האחרון ('+latest+'). אפשר לבדוק ימים אחרים.');return}el.innerHTML=serviceStory(aggregate(rows),latest)+'<button class="text-button" data-tab="reliability">בדיקת יום אחר ופירוט האיחורים ←</button>';bindTabs();}catch(e){if(n===epoch)error(el,quickReliability,'נתוני השירות לא נטענו כרגע. שאר המידע עדיין זמין.')}}

function scores(el){

 el.innerHTML=`<section class="section-intro"><span class="eyebrow">מאחורי המספרים</span><h2>מה אומרים המדדים על הקו?</h2><p>כאן נמצא הפירוט מקו פח ומהקו המוזהב: הנוסעים, השימוש במשאבים, העלות והסיבות לציון.</p><span class="date-chip">נוסעים ועלויות: ${esc(index.passengerPeriod)}</span></section>${record.groups.length?'':note('אין לקו נתונים לחישוב המדדים.')}${record.groups.map(g=>{
 const extra=annualExcess(g),ratio=g.avgCost>0&&g.costBenchmark>0?g.avgCost/g.costBenchmark:null;
 return `<section class="panel score-report"><div class="section-heading"><div><span class="eyebrow">${esc(g.category)}</span><h3>${esc(g.origin)} ← ${esc(g.dest)}</h3></div></div>${scope(g)}
 <div class="score-preview"><div class="pach"><span>קו פח · מדד אי־יעילות</span><strong>${g.sc?num(g.sc.score)+'/100':'אין ציון'}</strong><small>גבוה יותר = פחות יעיל לפי שיטת המדד. זה לא ציון לאיכות הנסיעה.</small></div><div class="gold"><span>הקו המוזהב</span><strong>${g.gold?num(g.gold.score)+'/100':'לא נכנס לדירוג'}</strong><small>${g.gold?'עובר את תנאי הסף של הקווים המצטיינים.':'הקו לא עבר את תנאי הסף. אין לו ציון אפס.'}</small></div></div>
 <div class="report-columns"><div><h3>איך משתמשים בקו?</h3><dl class="facts stacked">${fact('נוסעים בממוצע לנסיעה',num(g.avgRiders))}${fact('נוסעים בקטע העמוס, בממוצע',num(g.avgPeak))}${fact('נסיעות בשבוע',num(g.totalTrips))}${fact('נסיעות עם מעט נוסעים',num(g.percentLow)+'%','פחות מ־'+num(g.lowRiderTh)+' נוסעים בנסיעה; הסף מותאם לסוג הקו')}${fact('תחנות בלעדיות',num(g.exclusiveStops),'לפי הנתונים ששימשו את קו פח')}</dl></div>
 <div class="cost-panel"><h3>כמה עולה להסיע נוסע?</h3><strong class="cost-value">${g.avgCost>0?num(g.avgCost)+' ₪':'אין נתון'}</strong><p>עלות תפעולית לנוסע, לא מחיר הכרטיס.</p>${ratio!==null?`<div class="compare-row"><span>הקו הזה</span><i style="width:${Math.round(g.avgCost/Math.max(g.avgCost,g.costBenchmark)*100)}%"></i><b>${num(g.avgCost)} ₪</b></div><div class="compare-row benchmark"><span>ממוצע קבוצת ההשוואה</span><i style="width:${Math.round(g.costBenchmark/Math.max(g.avgCost,g.costBenchmark)*100)}%"></i><b>${num(g.costBenchmark)} ₪</b></div><p>${ratio>1?'גבוה בכ־'+num((ratio-1)*100)+'%':'נמוך בכ־'+num((1-ratio)*100)+'%'} מממוצע קבוצת ההשוואה: ${esc(g.category)}.</p>`:''}${extra>0&&!record.live?.rm?`<p><b>פער העלות באומדן שנתי: ${num(extra)} ₪</b><br><small>אומדן להשוואה, לא חיסכון מובטח.</small></p>`:''}</div></div>
 <section class="km-section"><h3>לאן הולכים הקילומטרים?</h3><div class="km-strip" aria-hidden="true"><i style="flex:${g.nonWastedKm||0}"></i><i style="flex:${g.wastedKm||0}"></i></div><dl class="facts">${fact('כל הנסיעות יחד',num(g.totalKm)+' ק״מ','בשבוע שבנתונים')}${fact('נסיעות שמעל סף הנוסעים',num(g.nonWastedKm)+' ק״מ')}${fact('נסיעות שמתחת לסף',num(g.wastedKm)+' ק״מ')}</dl><p class="caption">נסיעה עם מעט נוסעים אינה בהכרח מיותרת. ייתכן שהיא נותנת שירות שאין לו תחליף.</p></section>
 <section class="protections"><h3>מה חשוב להביא בחשבון?</h3>${(g.sc?.protections||[]).length?`<p>הגורמים הבאים הורידו יחד ${num(g.sc.totalDeduction)} נקודות מציון אי־היעילות:</p><ul>${g.sc.protections.map(p=>`<li><b>${esc(p.name)}</b><span>−${num(p.value)} נקודות</span><small>${esc(p.detail)}</small></li>`).join('')}</ul>`:'<p>בחישוב הזה לא הופעלה הפחתת ניקוד מיוחדת. זה אינו אומר שאין לקו חשיבות ציבורית.</p>'}</section>
</section>`;
 }).join('')}<section class="panel"><h3>רוצים לבדוק גם שינוי בלוח הזמנים?</h3><p>הסימולטור, ההמלצות לשינוי נסיעות והגדרות הניקוד האישיות זמינים בכלים המקוריים. הציונים כאן משתמשים בהגדרות הרגילות.</p>${links()}</section>`;
}

function passengers(el){
 el.innerHTML=`<section class="panel passenger-panel"><div class="section-heading"><div><span class="eyebrow">הנוסעים לאורך היום</span><h2>מתי הקו עמוס יותר?</h2></div><span class="date-chip">${esc(index.passengerPeriod)}</span></div><p>בחרו כיוון ויום כדי לראות איך מספר הנוסעים משתנה בין שעות היציאה.</p><div class="controls"><div><label for="sdir">כיוון</label><select id="sdir"><option value="">שני הכיוונים יחד</option>${[...new Set(record.schedule.map(r=>r[0]))].sort().map(d=>`<option>${esc(d)}</option>`).join('')}</select></div><div><label for="sday">יום בשבוע</label><select id="sday"><option value="">כל הימים</option>${['ראשון','שני','שלישי','רביעי','חמישי','שישי','שבת'].map((d,i)=>`<option value="${i+1}">${d}</option>`).join('')}</select></div></div><div id="passengerSummary"></div><div id="schedule"></div><p class="caption">אלה שעות היציאה בתקופה שבה נמדדו הנוסעים, ולא לוח זמנים עדכני לנסיעה היום. נתוני עלייה וירידה בכל תחנה עדיין לא מחוברים לעמוד הזה.</p></section>`;
 const draw=()=>{const rows=record.schedule.filter(r=>(!$('#sdir').value||String(r[0])===$('#sdir').value)&&(!$('#sday').value||r[2].map(String).includes($('#sday').value))).sort((a,b)=>a[1].localeCompare(b[1]));
 // For one selected day, weekly repetitions are apportioned across the row's operating days.
 const weighted=rows.map(r=>{const a=[...r];if($('#sday').value)a[5]=r[5]/Math.max(1,r[2].length);return a}),a=passengerStats(weighted);
 $('#passengerSummary').innerHTML=rows.length?`<div class="big-pair"><div><b>${num(a.avg)}</b><span>נוסעים בממוצע בנסיעה</span></div><div><b>${num(a.peak)}</b><span>בקטע העמוס, בממוצע</span></div></div>${hourlyChart(weighted)}`:'';
 $('#schedule').innerHTML=rows.length?`<details><summary>המספרים לכל שעת יציאה (${num(rows.length)} רשומות)</summary>${table(['כיוון','יציאה','ימי פעילות','נוסעים בנסיעה','בקטע העמוס','חזרות בשבוע','רכב'],rows.map(r=>[esc(r[0]),esc(r[1]),esc(r[2].map(i=>['','א׳','ב׳','ג׳','ד׳','ה׳','ו׳','שבת'][i]||i).join(', ')),num(r[3]),num(r[4]),num(r[5]),esc(r[6])]))}<p class="caption">״חזרות בשבוע״ מתייחס לכל ימי הפעילות שרשומים באותה שורה, גם כשנבחר יום אחד.</p></details>`:note('אין נסיעות בבחירה הזאת. נסו כיוון או יום אחר.');};$('#sdir').onchange=draw;$('#sday').onchange=draw;draw();
}

const variants=(all=true)=>`${all?'<option value="">כל הכיוונים והחלופות</option>':''}${record.variants.map(v=>`<option value="${esc(v.rid)}" ${variant===v.rid?'selected':''}>כיוון ${esc(v.dir)} · חלופה ${esc(v.alt)} · ${esc(routeName(v.name))}</option>`).join('')}`;
async function reliability(el){const n=epoch;el.innerHTML='<section class="panel" role="status">טוען את ימי המדידה…</section>';try{const days=await getDays();if(n!==epoch)return;el.innerHTML=`<section class="panel"><h2>איך הקו נסע ביום שבחרתם?</h2><div class="controls"><div><label for="day">יום מדידה</label><select id="day">${days.map(d=>`<option ${d.d===day?'selected':''}>${d.d}</option>`).join('')}</select></div><div><label for="variant">כיוון וחלופה</label><select id="variant">${variants()}</select></div></div><div id="reldata" aria-live="polite"></div></section>`;$('#day').onchange=()=>{day=$('#day').value;render()};$('#variant').onchange=()=>{variant=$('#variant').value;render()};if(!day){$('#reldata').innerHTML=note('טרם פורסמו ימי מדידה.');return}const d=await load('../bus/data/days/'+day+'.json');if(n!==epoch)return;const rows=rowsFor(d),a=aggregate(rows);if(!rows.length){$('#reldata').innerHTML=note('אין מדידה למסלול הזה ביום שבחרתם. אפשר לנסות יום אחר; היעדר מדידה לא מוכיח שהקו לא נסע.');return}const partial=a.sched>0&&a.obs/a.sched<.3;$('#reldata').innerHTML=`${partial?'<p class="note warning">פחות מ־30% מהנסיעות נצפו. ייתכן שהשידור חלקי; אין להסיק מכך שכל הנסיעות החסרות בוטלו.</p>':''}${serviceStory(a,day)}${table(['מצב ההגעה','מספר מדידות','אחוז'],['מוקדם ביותר מ־2 דקות','בזמן','איחור 5–10 דקות','איחור 10–20 דקות','איחור מעל 20 דקות'].map((s,i)=>[s,num(a.c[i]),pct(a.c[i],a.meas)]))}<h3>יציאה מהמוצא</h3><p>${pct(a.o[1],a.o.reduce((s,n)=>s+n,0))} מהיציאות שנמדדו היו בזמן.</p><details><summary>לפי שעה</summary>${table(['שעה','הגעות שנמדדו','בזמן'],Object.entries(a.hours).sort((a,b)=>+a[0]-b[0]).map(([h,[n,on]])=>[esc(h+':00'),num(n),pct(on,n)]))}</details><details><summary>עד איפה נצפו הנסיעות?</summary>${a.reachN?table(['תצפית','נסיעות'],['עד הסוף','חלק מהדרך','רק בהתחלה','שודר ולא זז'].map((l,i)=>[l,num(a.reach[i])])):note('אין פירוט התקדמות במסלול ליום הזה.')}</details><details><summary>אילו אוטובוסים נסעו בקו?</summary>${a.vehicleN?table(['סוג רכב','נסיעות','מתוך נסיעות עם פירוט רכב'],Object.entries(a.vehicle).map(([k,v])=>[esc(k),num(v),pct(v,a.vehicleN)]))+`<p>סוג הרכב לא זוהה ב־${num(Math.max(0,a.vehicleN-Object.values(a.vehicle).reduce((x,y)=>x+y,0)))} מתוך ${num(a.vehicleN)} נסיעות עם פירוט. ${num(Math.max(0,a.obs-a.vehicleN))} נסיעות נוספות ללא פירוט רכב.</p>`:note('אין פירוט סוגי רכב ליום הזה.')}</details><details id="stopProfile"><summary>באילו תחנות נרשמו איחורים?</summary><div id="profile"></div></details>`;$('#stopProfile').ontoggle=()=>{if($('#stopProfile')?.open)profile(n,rows)};}catch(e){if(n===epoch)error(el,()=>reliability(el))}}
async function profile(n,rows){const el=$('#profile');el.textContent='טוען מדידות בתחנות…';try{const [p,names]=await Promise.all([load('../bus/data/days/'+day+'.stops.json'),load('../bus/data/stops.json')]);if(n!==epoch)return;el.innerHTML=rows.map(r=>{const v=record.variants.find(v=>v.rid===String(r[0]));const ps=p[r[0]];return `<h3>כיוון ${esc(v?.dir)} · חלופה ${esc(v?.alt)}</h3>${ps?.length?table(['תחנה','הגעות שנמדדו','איחור ממוצע בדקות','בזמן'],ps.map(([code,count,avg,on])=>[esc(names[code]||code),num(count),num(avg/10),pct(on,count)])):note('לא פורסם פירוט תחנות לחלופה הזאת.')}`}).join('')}catch(e){if(n===epoch)error(el,()=>profile(n,rows))}}
async function route(el,preview=false){const n=epoch;if(!record.variants.some(v=>v.rid===variant))variant=record.variants[0]?.rid||'';el.innerHTML=`<section class="panel route-panel"><span class="eyebrow">על המפה</span><h2>איפה הקו עובר?</h2><label for="routeVariant">כיוון הנסיעה והמסלול</label><select id="routeVariant" style="max-width:100%">${variants(false)}</select><div id="routeContent" aria-live="polite">טוען מסלול מהארכיון…</div></section>`;$('#routeVariant').onchange=()=>{variant=$('#routeVariant').value;render()};const v=record.variants.find(v=>v.rid===variant),out=$('#routeContent');if(!v){out.innerHTML=note('אין לקו חלופה מזוהה בקטלוג המסלולים.')+fallbackStops();return}const rd=[record.makat,v.dir,v.alt].join('-').replace(/#/g,'H').replace(/\//g,'_');try{const lf=await load('../line-history/data/lines/'+encodeURIComponent(rd)+'.json');if(n!==epoch)return;const g=archiveGeometry(lf);if(!g)throw Error('no geometry');out.innerHTML=note('המסלול המתועד מ־'+g.date+'. מיקום האוטובוס בזמן אמת אינו מוצג כאן.')+`<div class="route-layout ${preview?'preview':''}"><div id="map" class="map" aria-label="מפת מסלול הקו"></div>${!g.points.length?note('אין תוואי כביש לגרסה הזאת; המפה מציגה תחנות בלבד.'):''}<div class="stops-column"><h3>${num(g.stops.length)} תחנות בדרך</h3><ol class="stoplist">${g.stops.map((s,i)=>`<li><strong>${i+1}</strong> ${esc(s[1])}<small>תחנה ${esc(s[0])}</small></li>`).join('')}</ol></div></div>`;if(window.L){map=L.map('map',{scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map);const pts=g.points.length?g.points:g.stops.map(s=>[s[2],s[3]]).filter(p=>p.every(Number.isFinite));if(g.points.length)L.polyline(g.points,{color:'#244ed8',weight:5}).addTo(map);g.stops.filter(s=>Number.isFinite(s[2])&&Number.isFinite(s[3])).forEach((s,i)=>{const node=document.createElement('span');node.textContent=(i+1)+'. '+s[1]+' · '+s[0];L.circleMarker([s[2],s[3]],{radius:5,color:'#244ed8',fillColor:'#fff',fillOpacity:1}).addTo(map).bindPopup(node)});if(pts.length)map.fitBounds(pts,{padding:[25,25],maxZoom:16});}else $('#map').textContent='המפה לא נטענה. רשימת התחנות מופיעה בהמשך.';}catch(e){if(n===epoch){out.innerHTML=note('לא נטענה גרסת מסלול לחלופה הזאת. רשימת התחנות הבאה היא מצילום הנוסעים, ללא סדר או הפרדה לכיוונים.')+fallbackStops()+ '<button id="retryMap">ניסיון נוסף לטעינת המסלול</button>';$('#retryMap').onclick=()=>route(el)}}}
function fallbackStops(){return record.stops.length?table(['תחנה','יישוב','קוד'],record.stops.map(s=>[esc(s[2]),esc(s[1]),esc(s[0])])):note('אין רשימת תחנות במקור הזה.');}
async function init(){try{index=await load('data/index.json');results();if(location.hash)await openLine(decodeURIComponent(location.hash.slice(1)));}catch(e){error($('#results'),init,'רשימת הקווים לא נטענה. אפשר לנסות שוב או להיכנס לאתרים הקיימים מהתפריט.');$('#status').textContent='טעינת הקטלוג נכשלה.'}}
window.addEventListener('hashchange',()=>{if(location.hash)openLine(decodeURIComponent(location.hash.slice(1)));else closeDetail()});init();

async function overlaps(el){const n=epoch;el.innerHTML='<section class="panel" role="status">טוען חפיפות בין קווים…</section>';try{const d=await load('../kavpach-overlap.json');if(n!==epoch)return;const score=row=>{const s=row?.[3],v=row?.[5];return v?.status==='estimated'&&Number.isFinite(s)&&Number.isFinite(v.selfPct)&&s>=0&&s<=100&&v.selfPct>=0&&v.selfPct<=100?(s+v.selfPct)/2:null};const rows=(d.lines?.[record.makat]||[]).filter(r=>score(r)!==null&&score(r)>=50).sort((a,b)=>score(b)-score(a));el.innerHTML=`<section class="panel"><h2>מי עוד נוסע בדרך הזאת?</h2><p>עודכן: ${esc(d.gen||'לא צוין במקור')}</p>${note('אלה קווים שחולקים חלק מהדרך עם הקו שבחרתם. כדאי לבדוק גם את הכיוון, השעה והתדירות לפני שבוחרים קו אחר.')}${rows.length?table(['קו','מסלול ההשוואה','דמיון משולב','תחנות משותפות','מהדרך משותף?','המקטע הרציף הארוך'],rows.map(r=>[index.lines.some(l=>l.makat===String(r[0]))?`<a href="#${encodeURIComponent(r[0])}">${esc(r[1])}</a>`:esc(r[1]),esc(routeName(r[2])),num(score(r))+'%',num(r[4])+' תחנות · '+num(r[3])+'%',num(r[5].sharedKm)+' ק״מ · '+num(r[5].selfPct)+'% מהקו שבחרתם',num(r[5].longestKm)+' ק״מ'])):note('במקור הנוכחי לא נמצאה חלופה שעוברת את סף החפיפה. אין פירוש הדבר שאין שירות אחר באזור.')}</section>`;}catch(e){if(n===epoch)error(el,()=>overlaps(el))}}
