import {annualExcess,scopeText} from './insights.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>n==null?'לא זמין':Number(n).toLocaleString('he-IL',{maximumFractionDigits:1});
const load=async p=>{const r=await fetch('https://raw.githubusercontent.com/Transit-Freak/kav-bochan/main/lines/data/'+p,{cache:'no-cache',signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(r.status);return r.json()};
const labels={lowTrips:'נסיעות עם מעט נוסעים',wastedKm:'קילומטרים בנסיעות דלילות',cost:'עלות לנוסע',riders:'נוסעים ועומס',deadhead:'נסיעות תפעוליות',highTrips:'נסיעות עם ביקוש גבוה',efficientKm:'קילומטרים עם ביקוש',avgRiders:'ממוצע נוסעים',peak:'עומס בקטע העמוס',volume:'נוסעים בשבוע'};
const dates=document.querySelector('#sourceDates'),out=document.querySelector('#lineCalculation');
async function init(){
 let idx;try{idx=await load('index.json');dates.innerHTML=`<p>נוסעים ועלויות: <b>${esc(idx.passengerPeriod)}</b><br>חישוב ציונים: ${esc(idx.scoringUpdated)}<br>עדכון סטטוס קווים: ${esc(idx.liveUpdated)}</p><p>תאריך מדידת השירות ותאריך המפה מופיעים ליד הנתון בעמוד הקו.</p>`;}catch{dates.textContent='תאריכי המקורות לא נטענו כרגע. אפשר לרענן ולנסות שוב.';return}
 const mk=decodeURIComponent(location.hash.slice(1));if(!mk)return;out.hidden=false;const row=idx.lines.find(r=>r.makat===mk);if(!row){out.textContent='הקו שבקישור אינו נמצא בקטלוג.';return}
 const back=document.querySelector('#backToLine');back.href='./#'+encodeURIComponent(mk);back.textContent='חזרה לקו '+row.number+' ←';out.textContent='טוען את פירוט החישוב לקו…';
 try{const bucket=await load(row.bucket+'.json?v='+idx.files[row.bucket]),r=bucket[mk];out.innerHTML=`<h2>פירוט החישוב לקו ${esc(r.number)}</h2><p>מק״ט ${esc(mk)}</p>${r.groups.length?'':'<p>אין לקו נתונים לחישוב הציונים.</p>'}${r.groups.map(g=>`<section><h3>${esc(g.category)} · ${esc(g.origin)} ← ${esc(g.dest)}</h3>${scopeText(g)?'<p class="note">'+esc(scopeText(g))+'</p>':''}<p>קו פח: ${num(g.sc?.rawScore)} נקודות לפני ההפחתות, ${num(g.sc?.score)} אחריהן. הקו המוזהב: ${g.gold?num(g.gold.score):'לא נכנס לדירוג'}.</p><div class="tablewrap"><table><thead><tr><th>רכיב</th><th>קו פח</th><th>הקו המוזהב</th></tr></thead><tbody>${Object.entries(labels).filter(([k])=>g.sc?.componentScores?.[k]!=null||g.gold?.componentScores?.[k]!=null).map(([k,l])=>`<tr><td>${esc(l)}</td><td>${num(g.sc?.componentScores?.[k])}</td><td>${num(g.gold?.componentScores?.[k])}</td></tr>`).join('')}</tbody></table></div>${annualExcess(g)>0&&!r.live?.rm?`<p>אומדן הפער השנתי: (${num(g.avgCost)} − ${num(g.costBenchmark)}) ₪ × ${num(g.avgRiders)} נוסעים × ${num(g.totalTrips)} נסיעות × 52 = ${num(annualExcess(g))} ₪.</p>`:''}${g.sc?.dhWeekly!=null?`<p>תצפיות על נסיעות תפעוליות: ${num(g.sc.dhWeekly)} בשבוע בממוצע. נתון נפרד מספירת הנוסעים.</p>`:''}</section>`).join('')}<p><button id="download">הורדת נתוני הקו (JSON)</button></p><details><summary>קובץ הנתונים המלא</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details>`;
 document.querySelector('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({sources:{passengerPeriod:idx.passengerPeriod,signatures:idx.signatures},line:r},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='line-'+mk+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 }catch{out.textContent='פירוט החישוב לקו לא נטען כרגע. אפשר לרענן ולנסות שוב.'}
}
init();
